use paste::paste;

macro_rules! vk_ext {
    ($name:ident, $ver:expr, $tag:expr) => {
        paste! {
            pub const [<$name _SPEC_VERSION>]:    u32          = $ver;
            pub const [<$name _EXTENSION_NAME>]:  &'static str = $tag;
        }
    }
}

//note --these following values I parsed out of the KhronosGroup/Vulkan-Headers git repository
//they may not align with the structs specified above
//in other words, at present, this may cause a bug if we rely on SPEC_VERSION
//
//today, SPEC_VERSION may be considered to indicate the most recent available version, even if the
//structures above do not reflect the most recent available layout
//
//in the future, this whole file should be generated by parsing the Vulkan-Headers

vk_ext![KHR_SURFACE,                                      25,  "VK_KHR_surface"];
vk_ext![KHR_SWAPCHAIN,                                    70,  "VK_KHR_swapchain"];
vk_ext![KHR_DISPLAY,                                      23,  "VK_KHR_display"];
vk_ext![KHR_DISPLAY_SWAPCHAIN,                            10,  "VK_KHR_display_swapchain"];

vk_ext![KHR_SAMPLER_MIRROR_CLAMP_TO_EDGE,                 3,   "VK_KHR_sampler_mirror_clamp_to_edge"];
vk_ext![KHR_MULTIVIEW,                                    1,   "VK_KHR_multiview"];
vk_ext![KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2,             2,   "VK_KHR_get_physical_device_properties2"];
vk_ext![KHR_DEVICE_GROUP,                                 4,   "VK_KHR_device_group"];
vk_ext![KHR_SHADER_DRAW_PARAMETERS,                       1,   "VK_KHR_shader_draw_parameters"];
vk_ext![KHR_MAINTENANCE1,                                 2,   "VK_KHR_maintenance1"];
vk_ext![KHR_DEVICE_GROUP_CREATION,                        1,   "VK_KHR_device_group_creation"];
vk_ext![KHR_EXTERNAL_MEMORY_CAPABILITIES,                 1,   "VK_KHR_external_memory_capabilities"];
vk_ext![KHR_EXTERNAL_MEMORY,                              1,   "VK_KHR_external_memory"];
vk_ext![KHR_EXTERNAL_MEMORY_FD,                           1,   "VK_KHR_external_memory_fd"];
vk_ext![KHR_EXTERNAL_SEMAPHORE_CAPABILITIES,              1,   "VK_KHR_external_semaphore_capabilities"];
vk_ext![KHR_EXTERNAL_SEMAPHORE,                           1,   "VK_KHR_external_semaphore"];
vk_ext![KHR_EXTERNAL_SEMAPHORE_FD,                        1,   "VK_KHR_external_semaphore_fd"];
vk_ext![KHR_PUSH_DESCRIPTOR,                              2,   "VK_KHR_push_descriptor"];
vk_ext![KHR_SHADER_FLOAT16_INT8,                          1,   "VK_KHR_shader_float16_int8"];
vk_ext![KHR_16BIT_STORAGE,                                1,   "VK_KHR_16bit_storage"];
vk_ext![KHR_INCREMENTAL_PRESENT,                          1,   "VK_KHR_incremental_present"];
vk_ext![KHR_DESCRIPTOR_UPDATE_TEMPLATE,                   1,   "VK_KHR_descriptor_update_template"];
vk_ext![KHR_IMAGELESS_FRAMEBUFFER,                        1,   "VK_KHR_imageless_framebuffer"];
vk_ext![KHR_CREATE_RENDERPASS_2,                          1,   "VK_KHR_create_renderpass2"];
vk_ext![KHR_SHARED_PRESENTABLE_IMAGE,                     1,   "VK_KHR_shared_presentable_image"];
vk_ext![KHR_EXTERNAL_FENCE_CAPABILITIES,                  1,   "VK_KHR_external_fence_capabilities"];
vk_ext![KHR_EXTERNAL_FENCE,                               1,   "VK_KHR_external_fence"];
vk_ext![KHR_EXTERNAL_FENCE_FD,                            1,   "VK_KHR_external_fence_fd"];
vk_ext![KHR_PERFORMANCE_QUERY,                            1,   "VK_KHR_performance_query"];
vk_ext![KHR_MAINTENANCE2,                                 1,   "VK_KHR_maintenance2"];
vk_ext![KHR_GET_SURFACE_CAPABILITIES_2,                   1,   "VK_KHR_get_surface_capabilities2"];
vk_ext![KHR_VARIABLE_POINTERS,                            1,   "VK_KHR_variable_pointers"];
vk_ext![KHR_GET_DISPLAY_PROPERTIES_2,                     1,   "VK_KHR_get_display_properties2"];
vk_ext![KHR_DEDICATED_ALLOCATION,                         3,   "VK_KHR_dedicated_allocation"];
vk_ext![KHR_STORAGE_BUFFER_STORAGE_CLASS,                 1,   "VK_KHR_storage_buffer_storage_class"];
vk_ext![KHR_RELAXED_BLOCK_LAYOUT,                         1,   "VK_KHR_relaxed_block_layout"];
vk_ext![KHR_GET_MEMORY_REQUIREMENTS_2,                    1,   "VK_KHR_get_memory_requirements2"];
vk_ext![KHR_IMAGE_FORMAT_LIST,                            1,   "VK_KHR_image_format_list"];
vk_ext![KHR_SAMPLER_YCBCR_CONVERSION,                     14,  "VK_KHR_sampler_ycbcr_conversion"];
vk_ext![KHR_BIND_MEMORY_2,                                1,   "VK_KHR_bind_memory2"];
vk_ext![KHR_MAINTENANCE3,                                 1,   "VK_KHR_maintenance3"];
vk_ext![KHR_DRAW_INDIRECT_COUNT,                          1,   "VK_KHR_draw_indirect_count"];
vk_ext![KHR_SHADER_SUBGROUP_EXTENDED_TYPES,               1,   "VK_KHR_shader_subgroup_extended_types"];
vk_ext![KHR_8BIT_STORAGE,                                 1,   "VK_KHR_8bit_storage"];
vk_ext![KHR_SHADER_ATOMIC_INT64,                          1,   "VK_KHR_shader_atomic_int64"];
vk_ext![KHR_SHADER_CLOCK,                                 1,   "VK_KHR_shader_clock"];
vk_ext![KHR_DRIVER_PROPERTIES,                            1,   "VK_KHR_driver_properties"];
vk_ext![KHR_SHADER_FLOAT_CONTROLS,                        4,   "VK_KHR_shader_float_controls"];
vk_ext![KHR_DEPTH_STENCIL_RESOLVE,                        1,   "VK_KHR_depth_stencil_resolve"];
vk_ext![KHR_SWAPCHAIN_MUTABLE_FORMAT,                     1,   "VK_KHR_swapchain_mutable_format"];
vk_ext![KHR_TIMELINE_SEMAPHORE,                           2,   "VK_KHR_timeline_semaphore"];
vk_ext![KHR_VULKAN_MEMORY_MODEL,                          3,   "VK_KHR_vulkan_memory_model"];
vk_ext![KHR_SHADER_TERMINATE_INVOCATION,                  1,   "VK_KHR_shader_terminate_invocation"];
vk_ext![KHR_FRAGMENT_SHADING_RATE,                        1,   "VK_KHR_fragment_shading_rate"];
vk_ext![KHR_SPIRV_1_4,                                    1,   "VK_KHR_spirv_1_4"];
vk_ext![KHR_SURFACE_PROTECTED_CAPABILITIES,               1,   "VK_KHR_surface_protected_capabilities"];
vk_ext![KHR_SEPARATE_DEPTH_STENCIL_LAYOUTS,               1,   "VK_KHR_separate_depth_stencil_layouts"];
vk_ext![KHR_UNIFORM_BUFFER_STANDARD_LAYOUT,               1,   "VK_KHR_uniform_buffer_standard_layout"];
vk_ext![KHR_BUFFER_DEVICE_ADDRESS,                        1,   "VK_KHR_buffer_device_address"];
vk_ext![KHR_DEFERRED_HOST_OPERATIONS,                     4,   "VK_KHR_deferred_host_operations"];
vk_ext![KHR_PIPELINE_EXECUTABLE_PROPERTIES,               1,   "VK_KHR_pipeline_executable_properties"];
vk_ext![KHR_PIPELINE_LIBRARY,                             1,   "VK_KHR_pipeline_library"];
vk_ext![KHR_SHADER_NON_SEMANTIC_INFO,                     1,   "VK_KHR_shader_non_semantic_info"];
vk_ext![KHR_COPY_COMMANDS_2,                              1,   "VK_KHR_copy_commands2"];
vk_ext![EXT_DEBUG_REPORT,                                 9,   "VK_EXT_debug_report"];
vk_ext![NV_GLSL_SHADER,                                   1,   "VK_NV_glsl_shader"];
vk_ext![EXT_DEPTH_RANGE_UNRESTRICTED,                     1,   "VK_EXT_depth_range_unrestricted"];
vk_ext![IMG_FILTER_CUBIC,                                 1,   "VK_IMG_filter_cubic"];
vk_ext![AMD_RASTERIZATION_ORDER,                          1,   "VK_AMD_rasterization_order"];
vk_ext![AMD_SHADER_TRINARY_MINMAX,                        1,   "VK_AMD_shader_trinary_minmax"];
vk_ext![AMD_SHADER_EXPLICIT_VERTEX_PARAMETER,             1,   "VK_AMD_shader_explicit_vertex_parameter"];
vk_ext![EXT_DEBUG_MARKER,                                 4,   "VK_EXT_debug_marker"];
vk_ext![AMD_GCN_SHADER,                                   1,   "VK_AMD_gcn_shader"];
vk_ext![NV_DEDICATED_ALLOCATION,                          1,   "VK_NV_dedicated_allocation"];
vk_ext![EXT_TRANSFORM_FEEDBACK,                           1,   "VK_EXT_transform_feedback"];
vk_ext![NVX_IMAGE_VIEW_HANDLE,                            2,   "VK_NVX_image_view_handle"];
vk_ext![AMD_DRAW_INDIRECT_COUNT,                          2,   "VK_AMD_draw_indirect_count"];
vk_ext![AMD_NEGATIVE_VIEWPORT_HEIGHT,                     1,   "VK_AMD_negative_viewport_height"];
vk_ext![AMD_GPU_SHADER_HALF_FLOAT,                        2,   "VK_AMD_gpu_shader_half_float"];
vk_ext![AMD_SHADER_BALLOT,                                1,   "VK_AMD_shader_ballot"];
vk_ext![AMD_TEXTURE_GATHER_BIAS_LOD,                      1,   "VK_AMD_texture_gather_bias_lod"];
vk_ext![AMD_SHADER_INFO,                                  1,   "VK_AMD_shader_info"];
vk_ext![AMD_SHADER_IMAGE_LOAD_STORE_LOD,                  1,   "VK_AMD_shader_image_load_store_lod"];
vk_ext![NV_CORNER_SAMPLED_IMAGE,                          2,   "VK_NV_corner_sampled_image"];
vk_ext![IMG_FORMAT_PVRTC,                                 1,   "VK_IMG_format_pvrtc"];
vk_ext![NV_EXTERNAL_MEMORY_CAPABILITIES,                  1,   "VK_NV_external_memory_capabilities"];
vk_ext![NV_EXTERNAL_MEMORY,                               1,   "VK_NV_external_memory"];
vk_ext![EXT_VALIDATION_FLAGS,                             2,   "VK_EXT_validation_flags"];
vk_ext![EXT_SHADER_SUBGROUP_BALLOT,                       1,   "VK_EXT_shader_subgroup_ballot"];
vk_ext![EXT_SHADER_SUBGROUP_VOTE,                         1,   "VK_EXT_shader_subgroup_vote"];
vk_ext![EXT_TEXTURE_COMPRESSION_ASTC_HDR,                 1,   "VK_EXT_texture_compression_astc_hdr"];
vk_ext![EXT_ASTC_DECODE_MODE,                             1,   "VK_EXT_astc_decode_mode"];
vk_ext![EXT_CONDITIONAL_RENDERING,                        2,   "VK_EXT_conditional_rendering"];
vk_ext![NV_CLIP_SPACE_W_SCALING,                          1,   "VK_NV_clip_space_w_scaling"];
vk_ext![EXT_DIRECT_MODE_DISPLAY,                          1,   "VK_EXT_direct_mode_display"];
vk_ext![EXT_DISPLAY_SURFACE_COUNTER,                      1,   "VK_EXT_display_surface_counter"];
vk_ext![EXT_DISPLAY_CONTROL,                              1,   "VK_EXT_display_control"];
vk_ext![GOOGLE_DISPLAY_TIMING,                            1,   "VK_GOOGLE_display_timing"];
vk_ext![NV_SAMPLE_MASK_OVERRIDE_COVERAGE,                 1,   "VK_NV_sample_mask_override_coverage"];
vk_ext![NV_GEOMETRY_SHADER_PASSTHROUGH,                   1,   "VK_NV_geometry_shader_passthrough"];
vk_ext![NV_VIEWPORT_ARRAY2,                               1,   "VK_NV_viewport_array2"];
vk_ext![NVX_MULTIVIEW_PER_VIEW_ATTRIBUTES,                1,   "VK_NVX_multiview_per_view_attributes"];
vk_ext![NV_VIEWPORT_SWIZZLE,                              1,   "VK_NV_viewport_swizzle"];
vk_ext![EXT_DISCARD_RECTANGLES,                           1,   "VK_EXT_discard_rectangles"];
vk_ext![EXT_CONSERVATIVE_RASTERIZATION,                   1,   "VK_EXT_conservative_rasterization"];
vk_ext![EXT_DEPTH_CLIP_ENABLE,                            1,   "VK_EXT_depth_clip_enable"];
vk_ext![EXT_SWAPCHAIN_COLOR_SPACE,                        4,   "VK_EXT_swapchain_colorspace"];
vk_ext![EXT_HDR_METADATA,                                 2,   "VK_EXT_hdr_metadata"];
vk_ext![EXT_EXTERNAL_MEMORY_DMA_BUF,                      1,   "VK_EXT_external_memory_dma_buf"];
vk_ext![EXT_QUEUE_FAMILY_FOREIGN,                         1,   "VK_EXT_queue_family_foreign"];
vk_ext![EXT_DEBUG_UTILS,                                  2,   "VK_EXT_debug_utils"];
vk_ext![EXT_SAMPLER_FILTER_MINMAX,                        2,   "VK_EXT_sampler_filter_minmax"];
vk_ext![AMD_GPU_SHADER_INT16,                             2,   "VK_AMD_gpu_shader_int16"];
vk_ext![AMD_MIXED_ATTACHMENT_SAMPLES,                     1,   "VK_AMD_mixed_attachment_samples"];
vk_ext![AMD_SHADER_FRAGMENT_MASK,                         1,   "VK_AMD_shader_fragment_mask"];
vk_ext![EXT_INLINE_UNIFORM_BLOCK,                         1,   "VK_EXT_inline_uniform_block"];
vk_ext![EXT_SHADER_STENCIL_EXPORT,                        1,   "VK_EXT_shader_stencil_export"];
vk_ext![EXT_SAMPLE_LOCATIONS,                             1,   "VK_EXT_sample_locations"];
vk_ext![EXT_BLEND_OPERATION_ADVANCED,                     2,   "VK_EXT_blend_operation_advanced"];
vk_ext![NV_FRAGMENT_COVERAGE_TO_COLOR,                    1,   "VK_NV_fragment_coverage_to_color"];
vk_ext![NV_FRAMEBUFFER_MIXED_SAMPLES,                     1,   "VK_NV_framebuffer_mixed_samples"];
vk_ext![NV_FILL_RECTANGLE,                                1,   "VK_NV_fill_rectangle"];
vk_ext![NV_SHADER_SM_BUILTINS,                            1,   "VK_NV_shader_sm_builtins"];
vk_ext![EXT_POST_DEPTH_COVERAGE,                          1,   "VK_EXT_post_depth_coverage"];
vk_ext![EXT_IMAGE_DRM_FORMAT_MODIFIER,                    1,   "VK_EXT_image_drm_format_modifier"];
vk_ext![EXT_VALIDATION_CACHE,                             1,   "VK_EXT_validation_cache"];
vk_ext![EXT_DESCRIPTOR_INDEXING,                          2,   "VK_EXT_descriptor_indexing"];
vk_ext![EXT_SHADER_VIEWPORT_INDEX_LAYER,                  1,   "VK_EXT_shader_viewport_index_layer"];
vk_ext![NV_SHADING_RATE_IMAGE,                            3,   "VK_NV_shading_rate_image"];
vk_ext![NV_RAY_TRACING,                                   3,   "VK_NV_ray_tracing"];
vk_ext![NV_REPRESENTATIVE_FRAGMENT_TEST,                  2,   "VK_NV_representative_fragment_test"];
vk_ext![EXT_FILTER_CUBIC,                                 3,   "VK_EXT_filter_cubic"];
vk_ext![QCOM_RENDER_PASS_SHADER_RESOLVE,                  4,   "VK_QCOM_render_pass_shader_resolve"];
vk_ext![EXT_GLOBAL_PRIORITY,                              2,   "VK_EXT_global_priority"];
vk_ext![EXT_EXTERNAL_MEMORY_HOST,                         1,   "VK_EXT_external_memory_host"];
vk_ext![AMD_BUFFER_MARKER,                                1,   "VK_AMD_buffer_marker"];
vk_ext![AMD_PIPELINE_COMPILER_CONTROL,                    1,   "VK_AMD_pipeline_compiler_control"];
vk_ext![EXT_CALIBRATED_TIMESTAMPS,                        1,   "VK_EXT_calibrated_timestamps"];
vk_ext![AMD_SHADER_CORE_PROPERTIES,                       2,   "VK_AMD_shader_core_properties"];
vk_ext![AMD_MEMORY_OVERALLOCATION_BEHAVIOR,               1,   "VK_AMD_memory_overallocation_behavior"];
vk_ext![EXT_VERTEX_ATTRIBUTE_DIVISOR,                     3,   "VK_EXT_vertex_attribute_divisor"];
vk_ext![EXT_PIPELINE_CREATION_FEEDBACK,                   1,   "VK_EXT_pipeline_creation_feedback"];
vk_ext![NV_SHADER_SUBGROUP_PARTITIONED,                   1,   "VK_NV_shader_subgroup_partitioned"];
vk_ext![NV_COMPUTE_SHADER_DERIVATIVES,                    1,   "VK_NV_compute_shader_derivatives"];
vk_ext![NV_MESH_SHADER,                                   1,   "VK_NV_mesh_shader"];
vk_ext![NV_FRAGMENT_SHADER_BARYCENTRIC,                   1,   "VK_NV_fragment_shader_barycentric"];
vk_ext![NV_SHADER_IMAGE_FOOTPRINT,                        2,   "VK_NV_shader_image_footprint"];
vk_ext![NV_SCISSOR_EXCLUSIVE,                             1,   "VK_NV_scissor_exclusive"];
vk_ext![NV_DEVICE_DIAGNOSTIC_CHECKPOINTS,                 2,   "VK_NV_device_diagnostic_checkpoints"];
vk_ext![INTEL_SHADER_INTEGER_FUNCTIONS_2,                 1,   "VK_INTEL_shader_integer_functions2"];
vk_ext![INTEL_PERFORMANCE_QUERY,                          2,   "VK_INTEL_performance_query"];
vk_ext![EXT_PCI_BUS_INFO,                                 2,   "VK_EXT_pci_bus_info"];
vk_ext![AMD_DISPLAY_NATIVE_HDR,                           1,   "VK_AMD_display_native_hdr"];
vk_ext![EXT_FRAGMENT_DENSITY_MAP,                         1,   "VK_EXT_fragment_density_map"];
vk_ext![EXT_SCALAR_BLOCK_LAYOUT,                          1,   "VK_EXT_scalar_block_layout"];
vk_ext![GOOGLE_HLSL_FUNCTIONALITY1,                       1,   "VK_GOOGLE_hlsl_functionality1"];
vk_ext![GOOGLE_DECORATE_STRING,                           1,   "VK_GOOGLE_decorate_string"];
vk_ext![EXT_SUBGROUP_SIZE_CONTROL,                        2,   "VK_EXT_subgroup_size_control"];
vk_ext![AMD_SHADER_CORE_PROPERTIES_2,                     1,   "VK_AMD_shader_core_properties2"];
vk_ext![AMD_DEVICE_COHERENT_MEMORY,                       1,   "VK_AMD_device_coherent_memory"];
vk_ext![EXT_SHADER_IMAGE_ATOMIC_INT64,                    1,   "VK_EXT_shader_image_atomic_int64"];
vk_ext![EXT_MEMORY_BUDGET,                                1,   "VK_EXT_memory_budget"];
vk_ext![EXT_MEMORY_PRIORITY,                              1,   "VK_EXT_memory_priority"];
vk_ext![NV_DEDICATED_ALLOCATION_IMAGE_ALIASING,           1,   "VK_NV_dedicated_allocation_image_aliasing"];
vk_ext![EXT_BUFFER_DEVICE_ADDRESS,                        2,   "VK_EXT_buffer_device_address"];
vk_ext![EXT_TOOLING_INFO,                                 1,   "VK_EXT_tooling_info"];
vk_ext![EXT_SEPARATE_STENCIL_USAGE,                       1,   "VK_EXT_separate_stencil_usage"];
vk_ext![EXT_VALIDATION_FEATURES,                          4,   "VK_EXT_validation_features"];
vk_ext![NV_COOPERATIVE_MATRIX,                            1,   "VK_NV_cooperative_matrix"];
vk_ext![NV_COVERAGE_REDUCTION_MODE,                       1,   "VK_NV_coverage_reduction_mode"];
vk_ext![EXT_FRAGMENT_SHADER_INTERLOCK,                    1,   "VK_EXT_fragment_shader_interlock"];
vk_ext![EXT_YCBCR_IMAGE_ARRAYS,                           1,   "VK_EXT_ycbcr_image_arrays"];
vk_ext![EXT_HEADLESS_SURFACE,                             1,   "VK_EXT_headless_surface"];
vk_ext![EXT_LINE_RASTERIZATION,                           1,   "VK_EXT_line_rasterization"];
vk_ext![EXT_SHADER_ATOMIC_FLOAT,                          1,   "VK_EXT_shader_atomic_float"];
vk_ext![EXT_HOST_QUERY_RESET,                             1,   "VK_EXT_host_query_reset"];
vk_ext![EXT_INDEX_TYPE_UINT8,                             1,   "VK_EXT_index_type_uint8"];
vk_ext![EXT_EXTENDED_DYNAMIC_STATE,                       1,   "VK_EXT_extended_dynamic_state"];
vk_ext![EXT_SHADER_DEMOTE_TO_HELPER_INVOCATION,           1,   "VK_EXT_shader_demote_to_helper_invocation"];
vk_ext![NV_DEVICE_GENERATED_COMMANDS,                     3,   "VK_NV_device_generated_commands"];
vk_ext![EXT_TEXEL_BUFFER_ALIGNMENT,                       1,   "VK_EXT_texel_buffer_alignment"];
vk_ext![QCOM_RENDER_PASS_TRANSFORM,                       1,   "VK_QCOM_render_pass_transform"];
vk_ext![EXT_DEVICE_MEMORY_REPORT,                         1,   "VK_EXT_device_memory_report"];
vk_ext![EXT_ROBUSTNESS_2,                                 1,   "VK_EXT_robustness2"];
vk_ext![EXT_CUSTOM_BORDER_COLOR,                          12,  "VK_EXT_custom_border_color"];
vk_ext![GOOGLE_USER_TYPE,                                 1,   "VK_GOOGLE_user_type"];
vk_ext![EXT_PRIVATE_DATA,                                 1,   "VK_EXT_private_data"];
vk_ext![EXT_PIPELINE_CREATION_CACHE_CONTROL,              3,   "VK_EXT_pipeline_creation_cache_control"];
vk_ext![NV_DEVICE_DIAGNOSTICS_CONFIG,                     1,   "VK_NV_device_diagnostics_config"];
vk_ext![QCOM_render_pass_store_ops,                       2,   "VK_QCOM_render_pass_store_ops"];
vk_ext![NV_FRAGMENT_SHADING_RATE_ENUMS,                   1,   "VK_NV_fragment_shading_rate_enums"];
vk_ext![EXT_FRAGMENT_DENSITY_MAP_2,                       1,   "VK_EXT_fragment_density_map2"];
vk_ext![QCOM_rotated_copy_commands,                       0,   "VK_QCOM_rotated_copy_commands"];
vk_ext![EXT_IMAGE_ROBUSTNESS,                             1,   "VK_EXT_image_robustness"];
vk_ext![EXT_4444_FORMATS,                                 1,   "VK_EXT_4444_formats"];
vk_ext![NV_ACQUIRE_WINRT_DISPLAY,                         1,   "VK_NV_acquire_winrt_display"];
vk_ext![VALVE_MUTABLE_DESCRIPTOR_TYPE,                    1,   "VK_VALVE_mutable_descriptor_type"];
vk_ext![KHR_ACCELERATION_STRUCTURE,                       11,  "VK_KHR_acceleration_structure"];
vk_ext![KHR_RAY_TRACING_PIPELINE,                         1,   "VK_KHR_ray_tracing_pipeline"];
vk_ext![KHR_RAY_QUERY,                                    1,   "VK_KHR_ray_query"];

//vulkan_fuchsia.h
vk_ext![FUCHSIA_IMAGEPIPE_SURFACE,                        1,   "VK_FUCHSIA_imagepipe_surface"];

//vulkan_vi.h
vk_ext![NN_VI_SURFACE,                                    1,   "VK_NN_vi_surface"];

//vulkan_wayland.h
vk_ext![KHR_WAYLAND_SURFACE,                              6,   "VK_KHR_wayland_surface"];

//vulkan_win32.h
vk_ext![KHR_WIN32_SURFACE,                                6,   "VK_KHR_win32_surface"];
vk_ext![KHR_EXTERNAL_MEMORY_WIN32,                        1,   "VK_KHR_external_memory_win32"];
vk_ext![KHR_WIN32_KEYED_MUTEX,                            1,   "VK_KHR_win32_keyed_mutex"];
vk_ext![KHR_EXTERNAL_SEMAPHORE_WIN32,                     1,   "VK_KHR_external_semaphore_win32"];
vk_ext![KHR_EXTERNAL_FENCE_WIN32,                         1,   "VK_KHR_external_fence_win32"];
vk_ext![NV_EXTERNAL_MEMORY_WIN32,                         1,   "VK_NV_external_memory_win32"];
vk_ext![NV_WIN32_KEYED_MUTEX,                             2,   "VK_NV_win32_keyed_mutex"];
vk_ext![EXT_FULL_SCREEN_EXCLUSIVE,                        4,   "VK_EXT_full_screen_exclusive"];

//vulkan_xcb.h
vk_ext![KHR_XCB_SURFACE,                                  6,   "VK_KHR_xcb_surface"];

//vulkan_directfb.h
vk_ext![EXT_DIRECTFB_SURFACE,                             1,   "VK_EXT_directfb_surface"];

//vulkan_xrandr.h
vk_ext![EXT_ACQUIRE_XLIB_DISPLAY,                         1,   "VK_EXT_acquire_xlib_display"];

//vulkan_xlib.h
vk_ext![KHR_XLIB_SURFACE,                                 6,   "VK_KHR_xlib_surface"];

//vulkan_ggp.h
vk_ext![GGP_STREAM_DESCRIPTOR_SURFACE,                    1,   "VK_GGP_stream_descriptor_surface"];
vk_ext![GGP_FRAME_TOKEN,                                  1,   "VK_GGP_frame_token"];

//vulkan_ios.h
vk_ext![MVK_IOS_SURFACE,                                  3,   "VK_MVK_ios_surface"];

//vulkan_macos.h
vk_ext![MVK_MACOS_SURFACE,                                3,   "VK_MVK_macos_surface"];

//vulkan_android.h
vk_ext![KHR_ANDROID_SURFACE,                              6,   "VK_KHR_android_surface"];
vk_ext![ANDROID_EXTERNAL_MEMORY_ANDROID_HARDWARE_BUFFER,  3,   "VK_ANDROID_external_memory_android_hardware_buffer"];

//vulkan_metal.h
vk_ext![EXT_METAL_SURFACE,                                1,   "VK_EXT_metal_surface"];

//vulkan_beta.h
vk_ext![KHR_PORTABILITY_SUBSET,                           1,   "VK_KHR_portability_subset"];

